### ISSUE TITLE
conda install recipe

### ISSUE THREAD

**Issue by pdimens** [ericcombiolab/Pangaea#6]
I see that one of the TODO's is to make a conda recipe. Here is what that might look like:

```yaml
{% set version = "" %}
{% set sha256 = "" %}

package:
  name: pangaea
  version: '{{ version }}'

source:
  url: https://github.com/ericcombiolab/Pangaea/archive/refs/tags/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'harpy

build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  run_exports:
    - {{ pin_subpackage('pangaea', max_pin="x") }}
  script: |
    cd third_parties/rph_kmeans
    python3 setup.py install
    cd -
    cd cpptools && make && cd -
  entry_points:
    - pangaea = pangaea.__main__

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools-scm >=3.4
  run:
    - numpy
    - pandas
    - sklearn
    - snakemake
    - pysam
    - torch
    - rph_kmeans
    - pigz
    - bwa
    - samtools
    - seqtk
    - spades
    - metaphlan
    - megahit
    - spades >=3.15.3
    - flye
    - quickmerge
    - metabat2
    - athena
test:
  commands:
    - "pangaea"

about:
  home: "https://github.com/ericcombiolab/Pangaea"
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: "A metagenome assembler for the linked-reads with high-barcode specificity ."
  dev_url: "https://github.com/ericcombiolab/Pangaea"

extra:
  recipe-maintainers:
    - ericcombiolab
```
